## =============================================================================
## 06_tables.R — Generate all LaTeX tables
## apep_0496: Education Priority Labels and Housing Markets in France
## =============================================================================

source("00_packages.R")

data_dir <- "../data"
tables_dir <- "../tables"
dir.create(tables_dir, showWarnings = FALSE)

## ---------------------------------------------------------------------------
## Load data
## ---------------------------------------------------------------------------

dt <- readRDS(file.path(data_dir, "analysis_data.rds"))
results <- readRDS(file.path(data_dir, "main_results.rds"))
robustness <- readRDS(file.path(data_dir, "robustness_results.rds"))

dt_near <- dt[abs(dist_signed) <= 2000]
dt_near[, log_price_m2 := log(price_m2)]

## ---------------------------------------------------------------------------
## Table 1: Summary Statistics (LaTeX)
## ---------------------------------------------------------------------------

cat("=== Table 1: Summary Statistics ===\n")

stats_all <- dt_near[, .(
  N = format(.N, big.mark = ","),
  `Mean Price/m²` = format(round(mean(price_m2)), big.mark = ","),
  `SD Price/m²` = format(round(sd(price_m2)), big.mark = ","),
  `Median Price/m²` = format(round(median(price_m2)), big.mark = ","),
  `Mean Surface` = round(mean(surface_reelle_bati, na.rm = TRUE), 1),
  `\\% Apartment` = round(100 * mean(type_local == "Appartement"), 1)
)]

stats_rep <- dt_near[rep_side == 1, .(
  N = format(.N, big.mark = ","),
  `Mean Price/m²` = format(round(mean(price_m2)), big.mark = ","),
  `SD Price/m²` = format(round(sd(price_m2)), big.mark = ","),
  `Median Price/m²` = format(round(median(price_m2)), big.mark = ","),
  `Mean Surface` = round(mean(surface_reelle_bati, na.rm = TRUE), 1),
  `\\% Apartment` = round(100 * mean(type_local == "Appartement"), 1)
)]

stats_nonrep <- dt_near[rep_side == 0, .(
  N = format(.N, big.mark = ","),
  `Mean Price/m²` = format(round(mean(price_m2)), big.mark = ","),
  `SD Price/m²` = format(round(sd(price_m2)), big.mark = ","),
  `Median Price/m²` = format(round(median(price_m2)), big.mark = ","),
  `Mean Surface` = round(mean(surface_reelle_bati, na.rm = TRUE), 1),
  `\\% Apartment` = round(100 * mean(type_local == "Appartement"), 1)
)]

tex_tab1 <- c(
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Summary Statistics: Property Transactions Near REP/Non-REP Boundaries}",
  "\\label{tab:summary}",
  "\\begin{adjustbox}{max width=\\textwidth}",
  "\\begin{tabular}{lcccccc}",
  "\\toprule",
  " & N & Mean Price/m\\textsuperscript{2} & SD & Median & Mean Surface & \\% Apt \\\\",
  "\\midrule",
  paste0("All & ", paste(stats_all, collapse = " & "), " \\\\"),
  paste0("REP Side & ", paste(stats_rep, collapse = " & "), " \\\\"),
  paste0("Non-REP Side & ", paste(stats_nonrep, collapse = " & "), " \\\\"),
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{adjustbox}",
  "\\begin{tablenotes}",
  "\\small",
  "\\item \\textit{Notes:} Sample restricted to transactions within 2km of a REP/non-REP coll\\`ege catchment boundary. Prices in euros per square meter. Data: DVF g\\'eolocallis\\'e 2020--2024.",
  "\\end{tablenotes}",
  "\\end{table}"
)

writeLines(tex_tab1, file.path(tables_dir, "table1_summary.tex"))
cat("  Saved table1_summary.tex\n")

## ---------------------------------------------------------------------------
## Table 2: Main RDD Results (already generated by 03_main_analysis.R)
## ---------------------------------------------------------------------------

cat("=== Table 2: Main RDD (already in table2_parametric_rdd.tex) ===\n")

## ---------------------------------------------------------------------------
## Table 3: Robustness — Bandwidth sensitivity + donut + kernels
## ---------------------------------------------------------------------------

cat("=== Table 3: Robustness ===\n")

bw_results <- fread(file.path(tables_dir, "bandwidth_sensitivity.csv"))
donut_results <- fread(file.path(tables_dir, "donut_specifications.csv"))

tex_tab3 <- c(
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Robustness: Bandwidth Sensitivity and Donut Specifications}",
  "\\label{tab:robustness}",
  "\\begin{adjustbox}{max width=\\textwidth}",
  "\\begin{tabular}{lccccc}",
  "\\toprule",
  "Specification & Coefficient & SE & 95\\% CI & Bandwidth & N\\textsubscript{eff} \\\\",
  "\\midrule",
  "\\multicolumn{6}{l}{\\textit{Panel A: Bandwidth Sensitivity}} \\\\"
)

for (i in seq_len(nrow(bw_results))) {
  row <- bw_results[i]
  label <- paste0(row$bw_multiple, "\\texttimes{} optimal")
  if (row$bw_multiple == 1.0) label <- "Optimal (baseline)"
  tex_tab3 <- c(tex_tab3, paste0(
    label, " & ",
    round(row$coef, 4), " & ",
    round(row$se, 4), " & [",
    round(row$ci_lower, 4), ", ", round(row$ci_upper, 4), "] & ",
    round(row$bandwidth, 0), " & ",
    format(row$n_eff, big.mark = ","), " \\\\"
  ))
}

tex_tab3 <- c(tex_tab3,
  "\\midrule",
  "\\multicolumn{6}{l}{\\textit{Panel B: Donut Specifications}} \\\\"
)

for (i in seq_len(nrow(donut_results))) {
  row <- donut_results[i]
  tex_tab3 <- c(tex_tab3, paste0(
    "Exclude $\\pm$", row$donut_m, "m & ",
    round(row$coef, 4), " & ",
    round(row$se, 4), " & & & ",
    format(row$n_eff, big.mark = ","), " \\\\"
  ))
}

tex_tab3 <- c(tex_tab3,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{adjustbox}",
  "\\begin{tablenotes}",
  "\\small",
  "\\item \\textit{Notes:} Panel A varies the bandwidth around the MSE-optimal choice from Calonico, Cattaneo, and Titiunik (2014). Panel B excludes transactions within the specified distance of the boundary. Triangular kernel throughout. Standard errors clustered at the commune level.",
  "\\end{tablenotes}",
  "\\end{table}"
)

writeLines(tex_tab3, file.path(tables_dir, "table3_robustness.tex"))
cat("  Saved table3_robustness.tex\n")

## ---------------------------------------------------------------------------
## Table 4: Covariate balance
## ---------------------------------------------------------------------------

cat("=== Table 4: Covariate Balance ===\n")

balance <- fread(file.path(tables_dir, "covariate_balance.csv"))

tex_tab4 <- c(
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Covariate Balance at REP/Non-REP Boundaries}",
  "\\label{tab:balance}",
  "\\begin{tabular}{lcccc}",
  "\\toprule",
  "Covariate & RDD Coefficient & SE & \\textit{p}-value & Bandwidth \\\\",
  "\\midrule"
)

cov_labels <- c(
  surface_reelle_bati = "Surface (m\\textsuperscript{2})",
  nombre_pieces_principales = "Number of Rooms",
  pct_apartment = "Share Apartments"
)

for (i in seq_len(nrow(balance))) {
  row <- balance[i]
  label <- ifelse(row$covariate %in% names(cov_labels),
                  cov_labels[row$covariate], row$covariate)
  tex_tab4 <- c(tex_tab4, paste0(
    label, " & ",
    round(row$coef, 3), " & ",
    round(row$se, 3), " & ",
    round(row$p_value, 3), " & ",
    round(row$bw, 0), " \\\\"
  ))
}

tex_tab4 <- c(tex_tab4,
  "\\bottomrule",
  "\\end{tabular}",
  "\\begin{tablenotes}",
  "\\small",
  "\\item \\textit{Notes:} Each row is a separate RDD regression using the covariate as the outcome. Under the identifying assumption, covariates should be smooth at the boundary (coefficients near zero). MSE-optimal bandwidth, triangular kernel.",
  "\\end{tablenotes}",
  "\\end{table}"
)

writeLines(tex_tab4, file.path(tables_dir, "table4_balance.tex"))
cat("  Saved table4_balance.tex\n")

cat("\nAll tables generated.\n")
